# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

#trigger:
#- main

#jobs:
#- job: c7-build
#  container: centos:7 # Docker Hub image reference
#
#steps:
#- script: |
#    .travis/do.sh
#  displayName: 'make'



jobs:
  - job: ce7
    pool:
      vmImage: 'ubuntu-18.04'
    container: centos:7
    steps:
    - script: yum install -y sudo
    - script:  sudo .travis/do.sh
    - script: cat /etc/*release*

  - job: ce8
    pool:
      vmImage: 'ubuntu-18.04'
    container: centos:8
    steps:
    - script: dnf install -y sudo
    - script:  sudo .travis/do.sh
    - script: cat /etc/*release*

  - job: ub18
    pool:
      vmImage: 'ubuntu-18.04'
    container: ubuntu:18.04
    steps:
    - script: apt install -y sudo
    - script:  sudo .travis/do.sh
    - script: cat /etc/*release*
